### ISSUE TITLE
Link from export_fig

### ISSUE THREAD

**Issue by altmany** [kupiqu/plot2svg#1]
I've switched the SVG link in [`export_fig`](https://github.com/altmany/export_fig) from @jschwizer99 's original plot2svg to your fork, since it seems that unfortunately Juerg hasn't updated his version in 3 years while yours is in active maintenance. Just a note to let you know your work is being noticed... Keep up the good work.

A recent related reference: https://undocumentedmatlab.com/blog/customizing-axes-tick-labels#comment-418799

**Comment by kupiqu** [comment]
Thank you for the positive feedback!

I am using plot2svg in several projects myself as well, so I'm quite motivated to support plot2svg... See very brief goals here: https://github.com/kupiqu/fig2svg

I must say though that I'm running very busy lately, but I hope to come back on track improving plot2svg soon enough.

Something that I want to do quite urgently is to push a fix for an issue in current bar plot implementation. I have a fix already in my local repo, but I want to enhance a corner user case, hopefully over the weekend...

Btw, feel free to submit new issues if you encounter any bug in my plot2svg implementation.

**Comment by kupiqu** [comment]
FYI: scatter plots and colorbars are now supported
