### ISSUE TITLE
Multiple plots with independent legends

### ISSUE THREAD

**Issue by JuanMChau** [kupiqu/plot2svg#12]
Greetings,

I've been trying to use

`
figure;
t = 0:0.01:5;

subplot( 1, 2, 1 );
plot( t, t, t, sin(t), t, cos(t) );
[~, l1] = legend( {'a', 'b', 'c'} );

subplot( 1, 2, 2 );
plot( t, t.^2, t, sinh(t), t, cosh(t) );
[~, l2] = legend( {'d', 'e', 'f'} );

plot2svg( 'myname.svg', '', '', [l1; l2] );
`

But the output svg file contains double legend l1 and l2 for each subplot. Am I using the function incorrectly for this kind of situation?

Kind regards,

**Comment by kupiqu** [comment]
fixed with commit a1aea03a9eb39f65648dcdeeb8dc09d71078f29f

**Comment by kupiqu** [comment]
it wasn't implemented. now you can do it as follows:

`plot2svg( 'myname.svg', '', '', {l1 l2} );`

**Comment by JuanMChau** [comment]
Thank you for the quick response! I was thinking about the same fix in case there was nothing else planned. :D
