### ISSUE TITLE
Add fig2svg as a Github repo on Matlab File Exchange

### ISSUE THREAD

**Issue by altmany** [kupiqu/plot2svg#16]
It would be good if you would upload this repo to the Matlab File Exchange - makes it easier to find and to integrate in Matlab

**Comment by kupiqu** [comment]
Yes, thank you, but I actually prefer not (not a fan of Matlab policies). If someone is interested and willing to do it, that person can go ahead (forking this repo if needed).

I'll leave this open, so it has more visibility.

**Comment by kupiqu** [comment]
Commit e94f240dcca7845205c089baa937883c312a1fc7 may increase the visibility of this repo for users that may call fig2svg via other toolboxes, such as export_fig (if it uses fig2svg instead of plot2svg) or DynaSim (when I replace plot2svg by fig2svg).

Closing...

**Comment by kupiqu** [comment]
@altmany, I asked Github to detach this repo from being a fork of plot2svg. Once done, I will add it to Matlab File Exchange.

**Comment by kupiqu** [comment]
Done: https://www.mathworks.com/matlabcentral/fileexchange/71301-fig2svg

**Comment by altmany** [comment]
:-)
