### ISSUE TITLE
yyaxis left/right --> Error: Object Copy of Axes with multiple coordinate systems is not supported.

### ISSUE THREAD

**Issue by Pekkaino** [kupiqu/plot2svg#17]
I'm trying to save a figure using fig2svg, but I encounter issues as soon as a figure has two y-axes. Even in the simplest of cases, e.g.

          >> figure
          >> yyaxis left
          >> plot(rand(3))
          >> yyaxis right
          >> plot(rand(3))
          >> fig2svg

copyobj gives the following error message:
 "Object Copy of Axes with multiple coordinate systems is not supported."

Is there a workaround for this?

**Comment by kupiqu** [comment]
Ok, copyobj fails when there is more than 1 axes in a figure.
I fixed that easily with try/catch (this is similar to what export_fig does actually).

Note that there is another issue, which is that fig2svg does not support yet for more than 1 axes, so only the last one is actually exported.

While I see how to implement that, a workaround is to use plotyy, which is not as convenient but does the job...

Closing this issue with commit e1906fd3ee28458dc85740b93d99a04b6a91cb73

It would be great if you could open a new issue specifically about supporting yyaxis in fig2svg.

**Comment by Pekkaino** [comment]
Thanks!
