### ISSUE TITLE
fig2svg does not support yyaxis

### ISSUE THREAD

**Issue by Pekkaino** [kupiqu/plot2svg#18]
When solving one issue, another one appeared: fig2svg does not support (yet) for more than 1 axes (using yyaxis), and as a result only the last one is actually exported.

**Comment by kupiqu** [comment]
fixed with commit 792613b0328716b3c4189ab7dbc409dfa6eb0854

**Comment by kupiqu** [comment]
@Pekkaino please give it a try...
