### ISSUE TITLE
missing variable param1

### ISSUE THREAD

**Issue by tkietzma** [kupiqu/plot2svg#2]
In line 136/137, the code assigns the contents of 'param1' to paperpos(3) and (4). 'param1' does not exist, however, leading to an error. 

To fix this, once can use figuresize, which is tested for existence in line 135. Updated code will be:

  if nargin >= 6 && ~isempty(figuresize)
    paperpos(3) = figuresize(1);
    paperpos(4) = figuresize(2);
  end

**Comment by kupiqu** [comment]
fixed with commit 47ff679f84b56574138a10a4282fff5ae90415b1

**Comment by kupiqu** [comment]
and thanks for letting me know about the bug!
