### ISSUE TITLE
Errorbars in legend not plotted in svg

### ISSUE THREAD

**Issue by JoTrab** [kupiqu/plot2svg#20]
I guess it is because the _[Hleg, LegObj] = legend()_ behaviour is depreceated since 2014b.
the legend is now retrieved with a single output.  
Using two outputs the  _ErrorBar_  Object becomes a  _Group_ object in the graphics array. 
I tried fixing it by basically making two figures, one with the old legend behaviour, one with the new behaviour and replacing the _Group_ LegObj with the _ErrorBar_ LegObj but it seems  ErrorBar object is not recognized
  _(Error in fig2svg>axchild2svg (line 2206)
              yerrorbar_x = (yerrorbar_x*axpos(3)+axpos(1))*paperpos(3);)_

**Comment by kupiqu** [comment]
> I guess it is because the [Hleg, LegObj] = legend() behaviour is depreceated since 2014b.
the legend is now retrieved with a single output.

EDIT: With a single output there is no way to reproduce the look and feel of the legend in fig2svg (or perhaps I should say that I didn't find how last time I checked, I think it's not possible, but would be happy if shown wrong), so that's a trick to be able to do so.

Can you attach a minimal code example to reproduce the issue? I assume you passed the legendIcons to fig2svg, right?

**Comment by JoTrab** [comment]
Yes, I passed the legendIcons. 
legend appearance minimal working example:
_figure;
errorbar(1:5:100,1:5:100,0.5*(1:5:100), 0.5*(1:5:100),...
    'o','Linewidth',3,'MarkerSize',10)
[a,b] = legend('errorbars')

figure;
errorbar(1:5:100,1:5:100,0.5*(1:5:100), 0.5*(1:5:100),...
    'o','Linewidth',3,'MarkerSize',10)
[c] = legend('errorbars')_

If you compare the figures you see that the errorbar legend entry behaviour is different.
The way fig2svg works the old behaviour is always executed.

I tried to adapt fig2svg by inserting the following code and get the mentioned error:

_h1 = gcf;
ax1 = gca;
legNew = legend(gca);
ax_children = get(gca, 'children')
leg_strings = get(ax_children, 'displayname');
delElem = []
for iiii = 1:length(leg_strings)
    if isempty(leg_strings{iiii}) == 1
        delElem = [delElem iiii]
    end
end
leg_strings(delElem) = [] ;
ax_children(delElem) = [] ;
%test = [leg_strings ax_children]

hh = figure;
new = copyobj(ax1 ,hh);
[a,legendIcons] = legend(new,legNew.String) ;
legendIcons2 = gobjects(length(leg_strings) + length(ax_children),1)
legendIcons2(1:length(leg_strings)) = legendIcons(1:length(leg_strings)) ;
legendIcons2(length(leg_strings)+1:end) = ax_children ;_

**Comment by kupiqu** [comment]
please use code format (code lines in between of ` ``` ` lines) and please include the call to the fig2svg function in the code example

**Comment by kupiqu** [comment]
I ran the code and I see what you mean now.

I realize that errorbars and legends are supported but not errorbars in legends :(

Not sure how easy or difficult this will be to implement...

**Comment by kupiqu** [comment]
If interested, you could see how legends were implemented for Matlab > 2014a and submit a pull request for errorbars.

**Comment by kupiqu** [comment]
Please see README.md

**Comment by kupiqu** [comment]
Currently unmaintained
