### ISSUE TITLE
Fontsize changes when passing Legend Icons

### ISSUE THREAD

**Issue by chri4354** [kupiqu/plot2svg#22]
Hi, Thank you for this fantastic package. I noticed however that when passing the legend icons argument (as recommended by warning message), the legend is plotted with a different fontsize then the rest of the axes.

**Comment by kupiqu** [comment]
Can you please give me a minimal code snippet to reproduce and debug the issue?

I need a MCVE (a minimal, complete and verifiable example) code that I can try. Without this it's much more complicated to fix issues.

**Comment by kupiqu** [comment]
Closing this due to no response
