### ISSUE TITLE
Horizontal bar plots

### ISSUE THREAD

**Issue by JuanMChau** [kupiqu/plot2svg#23]
Horizontal bar plots **barh(...)** are being saved as vertical due to the code not considering the Bar.Horizontal property.

**Comment by kupiqu** [comment]
It's a bit more complicated than that as it needs full implementation, but yes, they are not currently supported

**Comment by kupiqu** [comment]
If interested, you could see how regular bar plots were implemented for Matlab > 2014a and submit a pull request for horizontal bar plots.

**Comment by kupiqu** [comment]
Please see README.md

**Comment by kupiqu** [comment]
Currently unmaintained
