### ISSUE TITLE
Matrix dimensiosn must agree 

### ISSUE THREAD

**Issue by gupta353** [kupiqu/plot2svg#24]
When I plot a 13 x-y data-set with the following 'markertypes':  
       markertype={'o','^','*','x','s','d','o','^','*','x','s','o','^'};
I get the error attached in the notepad
[fig2svg_issue.txt](https://github.com/kupiqu/fig2svg/files/4246650/fig2svg_issue.txt)

**Comment by kupiqu** [comment]
I need a minimal example that reproduces the issue to fix this

**Comment by gupta353** [comment]
I have attached the script and data that I am am using. You will need to modify the 7th line of the script to specify the path in which you will keep the data folder (the one that I have provided). Please let me know if anything else is required.

[wq_different_stations.txt](https://github.com/kupiqu/fig2svg/files/4247651/wq_different_stations.txt)
[tot_diss_solids.zip](https://github.com/kupiqu/fig2svg/files/4247666/tot_diss_solids.zip)

**Comment by kupiqu** [comment]
Your script points to third party functions (varycolor) and prompts errors with textscan, both in Matlab and in Octave.

I made the following minimal example code:

```
markertype={'.', 'o', '+', '*', 'x', 's', 'd', 'p', 'h', '^', 'v', '<', '>'};

colorset = varycolor(numel(markertype));

figure
hold on

for i = 1:numel(markertype)
  scatter([2 3], [i i], markertype{i}, 'markeredgecolor', colorset(i, :), 'markerfacecolor', colorset(i,:));
  plot([1 4], [i i], markertype{i}, 'markeredgecolor', colorset(i, :), 'markerfacecolor', colorset(i,:))
end

fig2svg('test.svg')
```

There is no Matlab error for me with it, but I found and fixed few marker errors (some markers were not diplayed for scatter plots, and some sizes didn't look as in Matlab): https://github.com/kupiqu/fig2svg/commit/9b16f135ca585168dd7aad6249f93dfd5ecf0684

**Comment by kupiqu** [comment]
I'm closing this, if there are still issues, please tell and submit a minimal (really minimal) example code.
