### ISSUE TITLE
Outputs malformed svg file when axis labels use U+2212 character

### ISSUE THREAD

**Issue by HarryDymond** [kupiqu/plot2svg#27]
If the figure contains axis labels that use the U+2212 ("minus") character, fig2svg generates a malformed file.

I've attached a .fig file that demonstrates the problem. I'm using Matlab R2018a on macOS Mojave. The figure exports to svg fine with MATLAB's print command.

The figure was generated with the following code:

figure; plot([-2:0.1:-1],[2:-0.1:1]); num2eng(gca,0,0,0,4,0,1);

Using num2eng [from the MATLAB file exchange](https://uk.mathworks.com/matlabcentral/fileexchange/67740-num2eng)

[fig2svg_issue.zip](https://github.com/kupiqu/fig2svg/files/4967611/fig2svg_issue.zip)

**Comment by HarryDymond** [comment]
I've just seen in the readme that you've now abandoned this project. Please could you update your entry on the MATLAB file exchange to make this more obvious?

**Comment by kupiqu** [comment]
Thanks for the note. I am now discussing about fig2svg with Yair Altman (dev of export_fig). For now we need to wait until a decision for the future of fig2svg is made...

**Comment by HarryDymond** [comment]
Thanks for the update

Now, an update on this specific issue, in case development re-starts:

After a little further experimenting, I believe that _any_ "extended" characters in tick labels will cause this issue:

e.g.:
```
figure;
plot([-2:0.1:-1],[2:-0.1:1]);
axH = gca;
axH.XTickLabel{1} = char(956); % replaces first tick label on the x-axis with the Greek character "mu"
```

Exporting the figure above with fig2svg results in a malformed svg file.

**Comment by kupiqu** [comment]
Currently unmaintained
