### ISSUE TITLE
Export with Transparent Background

### ISSUE THREAD

**Issue by RoyiAvital** [kupiqu/plot2svg#28]
I would like to have an SVG with transparent background.

Minimal Example:

```matlab
figure();
plot(1:10);
set(gcf(), 'Color', 'none');
set(gca(), 'Color', 'none');
fig2svg('test.svg');
```

Yet the output doesn't have transparent background.
Any way to have it?

**Comment by kupiqu** [comment]
Right, this should be relatively easy to fix, but as mentioned in README, this repo is currently unmaintained. I would suggest filling a bug in mathworks to support this in matlab's built-in svg export
