### ISSUE TITLE
Scatter does not work well

### ISSUE THREAD

**Issue by sharahamo** [kupiqu/plot2svg#3]
@kupiqu scatter plot does not work well

`Warning: Unhandled child type: scatter`

**Comment by kupiqu** [comment]
This is actually known as you can see here: https://github.com/kupiqu/fig2svg, but thanks for reporting.

Unfortunately, I didn't have much time recently to work in plot2svg. I hope to find some spare time to continue porting these features soon, but I'm afraid this won't happen before Jun 15th.

**Comment by sharahamo** [comment]
@kupiqu my apologies I failed to notice the readme file. Hopefully it will work soon as I am working on my thesis. I tried using MATLAB's function but somehow I hate how it handles the element and the file is unbelievably big (for eg 1MB with MATLAB's vs 300KB with plot2svg)

**Comment by kupiqu** [comment]
fixed with commit 8a1cb9416fcbc779bbb69a17935e3a249d98e0e7
