### ISSUE TITLE
Colorbar not working

### ISSUE THREAD

**Issue by ghost** [kupiqu/plot2svg#4]
I am using Matlab 2018a, and saving a figure with a colorbar is still not working. Error message is
Warning: Unhandled main figure child type: colorbar

**Comment by kupiqu** [comment]
This is known as you can see here: https://github.com/kupiqu/fig2svg, but thanks for reporting.

Unfortunately, I didn't have much time recently to work in plot2svg. I hope to find some spare time to continue porting these features soon...

**Comment by ghost** [comment]
Ok. You wrote at https://github.com/jschwizer99/plot2svg/issues/2 on 29th November "Bars and Legends are implemented in my fork", so I assumed this version does support it already.

**Comment by kupiqu** [comment]
Yes, and they are indeed implemented (issues related to them, if any, are welcome).

Until very recently, nobody seemed to be bothered too much by these other missing components and I've been quite busy lately (and still am, although I hope to have some spare time next week...).

**Comment by ghost** [comment]
Ah, now I get it. With "Bars", you were actually not referring to colorbars, but to bars in the plots?! :)

**Comment by kupiqu** [comment]
Yes, I was referring to bar plots. Sorry for the confusion

**Comment by kupiqu** [comment]
fixed with commit be3100dbf0defe76795139bd4ef4543335211e99
